import {defineArrayMember, defineField, defineType} from 'sanity'

export const wallpaper = defineType({
  name: 'wallpaper',
  title: '壁纸',
  type: 'document',
  groups: [
    {name: 'basic', title: '基本信息', default: true},
    {name: 'assets', title: '文件资源'},
    {name: 'rights', title: '作者与版权'},
    {name: 'display', title: '展示设置'},
  ],
  initialValue: () => ({
    kind: 'image',
    status: 'published',
    featured: false,
    curated: false,
    popular: false,
    sortOrder: Date.now(),
    categoryRefs: [],
  }),
  fields: [
    defineField({
      name: 'title',
      title: '中文名称',
      type: 'string',
      group: 'basic',
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: 'titleEn',
      title: '英文名称',
      type: 'string',
      group: 'basic',
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: 'subtitle',
      title: '中文简介',
      type: 'text',
      rows: 2,
      group: 'basic',
      validation: (rule) => rule.max(240),
    }),
    defineField({
      name: 'subtitleEn',
      title: '英文简介',
      type: 'text',
      rows: 2,
      group: 'basic',
      validation: (rule) => rule.max(240),
    }),
    defineField({
      name: 'kind',
      title: '壁纸类型',
      type: 'string',
      group: 'basic',
      options: {
        list: [
          {title: '静态图片', value: 'image'},
          {title: '动态视频', value: 'video'},
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'categoryRefs',
      title: '分类（中文 / English）',
      description: '从分类字典选择；每一项都自带中文和英文名称，客户端切换语言时自动对应。',
      type: 'array',
      group: 'basic',
      of: [defineArrayMember({type: 'reference', to: [{type: 'category'}]})],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'localizedTags',
      title: '搜索标签（中文 / English）',
      description: '每一行是一组严格对应的中英文标签，搜索时两种语言都会命中。',
      type: 'array',
      group: 'basic',
      of: [defineArrayMember({type: 'localizedTag'})],
    }),
    defineField({
      name: 'categories',
      title: '旧版分类（兼容字段）',
      type: 'array',
      group: 'basic',
      of: [defineArrayMember({type: 'string'})],
      hidden: true,
    }),
    defineField({
      name: 'tags',
      title: '旧版标签（兼容字段）',
      type: 'array',
      group: 'basic',
      of: [defineArrayMember({type: 'string'})],
      hidden: true,
    }),
    defineField({
      name: 'thumbnail',
      title: '列表封面',
      description: '建议使用 16:10 或 16:9 横图，控制在 300KB 以内。',
      type: 'image',
      group: 'assets',
      options: {hotspot: true},
    }),
    defineField({
      name: 'image',
      title: '静态壁纸原图',
      type: 'image',
      group: 'assets',
      hidden: ({parent}) => parent?.kind !== 'image',
    }),
    defineField({
      name: 'video',
      title: '动态壁纸视频',
      description: '建议 MP4/HEVC，发行文件尽量控制在 100MB 以内。',
      type: 'file',
      group: 'assets',
      options: {accept: 'video/mp4,video/quicktime,video/*'},
      hidden: ({parent}) => parent?.kind !== 'video',
    }),
    defineField({
      name: 'previewVideo',
      title: '轻量预览视频',
      description: '用于首页自动播放和卡片悬停预览。建议 8 秒、540p；客户端首次加载后会永久缓存。',
      type: 'file',
      group: 'assets',
      options: {accept: 'video/mp4,video/x-m4v,video/*'},
      hidden: ({parent}) => parent?.kind !== 'video',
    }),
    defineField({
      name: 'width',
      title: '宽度（像素）',
      type: 'number',
      group: 'assets',
      validation: (rule) => rule.integer().positive(),
    }),
    defineField({
      name: 'height',
      title: '高度（像素）',
      type: 'number',
      group: 'assets',
      validation: (rule) => rule.integer().positive(),
    }),
    defineField({
      name: 'duration',
      title: '视频时长（秒）',
      type: 'number',
      group: 'assets',
      hidden: ({parent}) => parent?.kind !== 'video',
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: 'author',
      title: '作者',
      type: 'string',
      group: 'rights',
      initialValue: 'Foldwalls',
    }),
    defineField({
      name: 'licenseName',
      title: '授权说明',
      type: 'string',
      group: 'rights',
      initialValue: 'Foldwalls Original',
    }),
    defineField({
      name: 'sourceUrl',
      title: '来源链接',
      type: 'url',
      group: 'rights',
      validation: (rule) => rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'status',
      title: '上架状态',
      type: 'string',
      group: 'display',
      options: {
        list: [
          {title: '已上架', value: 'published'},
          {title: '已下架', value: 'hidden'},
        ],
        layout: 'radio',
      },
    }),
    defineField({
      name: 'featured',
      title: '首页推荐（Hero 轮播）',
      type: 'boolean',
      group: 'display',
      initialValue: false,
    }),
    defineField({
      name: 'curated',
      title: '精选分组',
      description: '勾选后会出现在首页“精选”。',
      type: 'boolean',
      group: 'display',
      initialValue: false,
    }),
    defineField({
      name: 'popular',
      title: '热门分组',
      description: '勾选后会出现在首页“热门”和探索页“最热”。',
      type: 'boolean',
      group: 'display',
      initialValue: false,
    }),
    defineField({
      name: 'sortOrder',
      title: '排序数字',
      description: '数字越大越靠前；新增内容会自动使用当前时间作为排序数字。',
      type: 'number',
      group: 'display',
      validation: (rule) => rule.integer().min(0),
    }),
    defineField({
      name: 'paletteStart',
      title: '主色起点（HEX）',
      type: 'string',
      group: 'display',
      initialValue: '#151821',
      validation: (rule) => rule.regex(/^#[0-9A-Fa-f]{6}$/, {name: 'HEX 颜色'}),
    }),
    defineField({
      name: 'paletteMiddle',
      title: '主色中点（HEX）',
      type: 'string',
      group: 'display',
      initialValue: '#30384A',
      validation: (rule) => rule.regex(/^#[0-9A-Fa-f]{6}$/, {name: 'HEX 颜色'}),
    }),
    defineField({
      name: 'paletteEnd',
      title: '主色终点（HEX）',
      type: 'string',
      group: 'display',
      initialValue: '#11131A',
      validation: (rule) => rule.regex(/^#[0-9A-Fa-f]{6}$/, {name: 'HEX 颜色'}),
    }),
  ],
  orderings: [
    {
      title: '运营排序',
      name: 'editorialOrder',
      by: [
        {field: 'sortOrder', direction: 'desc'},
        {field: '_createdAt', direction: 'desc'},
      ],
    },
    {title: '最近更新', name: 'recentlyUpdated', by: [{field: '_updatedAt', direction: 'desc'}]},
  ],
  preview: {
    select: {
      title: 'title',
      kind: 'kind',
      status: 'status',
      featured: 'featured',
      curated: 'curated',
      popular: 'popular',
      media: 'thumbnail',
    },
    prepare({title, kind, status, featured, curated, popular, media}) {
      const kindLabel = kind === 'video' ? '动态' : '图片'
      const statusLabel = status === 'published' ? '已上架' : '已下架'
      const groups = [featured && '推荐', curated && '精选', popular && '热门'].filter(Boolean)
      return {title: title || '未命名壁纸', subtitle: `${kindLabel} · ${statusLabel}${groups.length ? ` · ${groups.join(' / ')}` : ''}`, media}
    },
  },
})
